version: "3"
services:
  prisma-mysql:
    image: mysql:latest
    container_name: mysql-container-luciak
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mysql-image-database1k
    ports:
      - "3306:3306"
  prisma-redis:
    image: redis:latest
    container_name: redis-container-luciak
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
